### ISSUE TITLE
Type error: Cannot find module 'zod-fetch'

### ISSUE THREAD

**Issue by pablojsx** [mattpocock/zod-fetch#10]
I'm just learning Next but I have a clean T3 app running here:

https://t3-tests.vercel.app/

I just did a simple fetch inside a component and it worked fine then did a deploy and got an error:

`
Type error: Cannot find module 'zod-fetch' or its corresponding type declarations.
--
05:26:19.332 |  
05:26:19.332 | 1 \| import Link from "next/link";
05:26:19.333 | > 2 \| import { createZodFetcher } from "zod-fetch";
05:26:19.333 | \|                                  ^
05:26:19.333 | 3 \| import { z } from "zod";
05:26:19.333 | 4 \|
05:26:19.333 | 5 \| const zfetch = createZodFetcher();
`

The fetch:

` return await zfetch(
    z.array(z.unknown()),
    "https://jsonplaceholder.typicode.com/users")
    .then((data) => ({ robots: data }));`

Thanks for the help!

**Comment by mattpocock** [comment]
Did you install `zod-fetch` via npm?

**Comment by mattpocock** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-install

**Comment by pablojsx** [comment]
I'm sorry I noticed I didn't CD to the project folder and installed your package in the root, thanks for the help Matt
