### ISSUE TITLE
Suggestions: avoiding createZodFetcher and using it without a schema

### ISSUE THREAD

**Issue by arjunu** [mattpocock/zod-fetch#5]
Thanks for this handy util.

Two ideas that I think would help:

### 1. Ability to use `fetchWithZod` without having to call `createZodFetcher` 
If I do not want to use a custom fetcher, it would be nice to import `fetchWithZod` and use it directly
```
import { fetchWithZod } from "zod-fetch";

fetchWithZod(...)
```

### 2. Ability to use `fetchWithZod` without a schema
For consistency, I would like to use `fetchWithZod` everywhere and in some cases I don't want to validate the response either because it's gonna be a 204 or I want to ignore the response if `response.ok = true`

What do you think? I'd be happy to open a PR with these changes.

**Comment by mattpocock** [comment]
1. The annoying thing about having a singleton export of `fetchWithZod` would be having conflicting imports between _your_ fetchWithZod and the library's. So I'd prefer not to.

2. I'd also prefer not to make the function more polymorphic than it already is!
